### ISSUE TITLE
Trust List Design Considerations: Longevity, Network calls, Size minimization

### ISSUE THREAD

**Issue by decentralgabe** [decentralized-identity/trust-establishment#10]
At the last call, on June 13, where I was not present, I heard of an interesting discussion around whether _endorsements_ should be included inside of _Trust Lists_ as _Verifiable Credentials_. Since I was not privy to all the discussion, and I have little context I'll share my initial thoughts, and welcome many more from all of you....

More broadly there seems to be a question of "staleness" meaning -- how long can a `Trust List` be accepted. Unwinding this thought, a Trust List can be accepted as long as all of its contents are valid. Valid means the document contains, at the point of usage, _true statements_ from the perspective of the author(s) in addition to _resolvable_ when referencing an external document—a `Trust List` full of schema URIs that are dead links cannot be seen as valid. 

The [initial draft strawman](https://identity.foundation/trust-establishment/) I've spent some time on does not answer these questions. It also does not include [Verifiable Credentials](https://www.w3.org/TR/vc-data-model) at all. There are a number of downsides here, which I'll phrase as open questions:

1. How are Trust Lists hosted and published?
2. How are Trust Lists updated? We have a `version` field, but how can I make sure the version I'm looking at is the latest one?
3. [How can I undo an endorsement?](https://github.com/decentralized-identity/trust-establishment/issues/8)
4. Where are Trust Lists agreed upon and generated?
5. How do Trust Lists facilitate mass-endorsement? Meaning, 1000s of entities endorsing a single Trust List.

Some of these questions may be outside the scope of this specification, which really serves to define a data model. That said, I don't think the questions are outside the scope of the _work item_ which really should have good answers. Maybe that comes in the form of an implementers guide.

Additionally, I'd like to set out some design principles I think are worth striving towards:
- Resolve as few documents as possible when using a Trust List. The ideal is resolving just the Trust List and gaining *all information*.
- Strive for longevity of Trust Lists. Acknowledging that updating and un-endorsing can be cumbersome, we must assume that Trust Lists will have some kind of permanence.
- Strive for minimal Trust Lists. Trust Lists should not be megabytes of data. They should be small, and quickly transmitted. All unnecessary information should be removed. This is a driving factor for making Trust Lists [schema-based, instead of issuer-based -- though that option can be explored](https://github.com/decentralized-identity/trust-establishment/issues/9).

**Comment by decentralgabe** [comment]
tagging @csuwildcat @mikekebert @TelegramSam @bumblefudge for input!

**Comment by bumblefudge** [comment]
I'd break out # 5 in this list to a separate issue so we remember to come back to it later

**Comment by decentralgabe** [comment]
> 5\. How do Trust Lists facilitate mass-endorsement? Meaning, 1000s of entities endorsing a single Trust List.

https://github.com/decentralized-identity/trust-establishment/issues/11

**Comment by decentralgabe** [comment]
Broken out into two specs:
- https://identity.foundation/trust-establishment/sentiment-declaration/
- https://identity.foundation/trust-establishment/trusted-issuer-establishment/
