### ISSUE TITLE
Where can publication occur?

### ISSUE THREAD

**Issue by decentralgabe** [decentralized-identity/trust-establishment#4]
https://hackmd.io/a50I9MlkRVOQJOYgf7b3hA

**Comment by decentralgabe** [comment]
8/8:
- What ways are people comfortable expressing/publishing?
- Discovery. Passing URLs around. Mass aggregation. Handling versions.
- Could provide multiple examples across protocols of how to request/discover

**Comment by decentralgabe** [comment]
Discussed on 9/12: we need this as one of the few items for a first draft.

@csuwildcat  can you commit to a contribution within a week or two?

**Comment by csuwildcat** [comment]
@decentralgabe happy to articulate the DWN publication route, will add it to my list for this upcoming cycle
