### ISSUE TITLE
Do we really need all the formations?

### ISSUE THREAD

**Issue by jischr** [decentralized-identity/trust-establishment#47]
cc: @dtmcg

Do we really need all the formations (+ more that we aren't thinking of)? Or could one formation, like `set oriented` cover all of the use cases?

Pros:
- Ease of implementation from developer point of view
- Don't you have to implement all formations anyways? To be able to understand all/most trust documents that you want to read?

Con:
- Repetition of the statements

**Comment by dtmcg** [comment]
+1 for one formulation.
if we take that the output of processing any trust establishment doc, using any formulation, will be a set of unique triples (authorEntity, processedTopic, subjectEntity) 
then the only reason to have multiple formulations would be to allow someone to express this end state in a way which they can not in some other formulation. 
As per @jischr comment set oriented covers all use cases so makes all others redundant. (I would have a preference for  _topics_by_entity_  if it uses an array for its entities under the subject entity key as it would then be functionally equivalent to the set formulation)

**Comment by andorsk** [comment]
Discussion on DIF Jan 23 Call: 

* Agreement that we should reduce formations to just 1, probably `set oriented` is best candidate.
  * Possible modified `set-oriented` to restrict duplication?  `dup_allowed`.  Mixed positions. 
  * @TelegramSam should not be set. Should mechanically reject. Topics by entity or entities by topic accomplish same set of features without allowing duplications. 
  * `entities_by_topic` to `entries`
* Performance consideration: adding index. Decided to defer about this when it becomes a problem. 
* @jischr : to raise a PR. 

* TODO: Re-discuss this next week.

**Comment by jischr** [comment]
made #48 as a starting point
